// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNF3Gcnsu-x2aBIlqvv-7fk5x2sbvOL2w',
    appId: '1:83064937407:web:c97c0909afd5cdd7a49f0a',
    messagingSenderId: '83064937407',
    projectId: 'myauthentication-534e5',
    authDomain: 'myauthentication-534e5.firebaseapp.com',
    storageBucket: 'myauthentication-534e5.appspot.com',
    measurementId: 'G-7M8XJC3TS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTL2SYPDxFfTb6nanTUja_KQpx-DhkRs8',
    appId: '1:83064937407:android:908f2196c3fb1938a49f0a',
    messagingSenderId: '83064937407',
    projectId: 'myauthentication-534e5',
    storageBucket: 'myauthentication-534e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjhE-1RrtgsTVMeuA-G_eadHZgljfrpBA',
    appId: '1:83064937407:ios:d074797eeaa8c8eaa49f0a',
    messagingSenderId: '83064937407',
    projectId: 'myauthentication-534e5',
    storageBucket: 'myauthentication-534e5.appspot.com',
    iosClientId: '83064937407-p14mrgjpuppat9euqcft5aekpaana3e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileNumberAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjhE-1RrtgsTVMeuA-G_eadHZgljfrpBA',
    appId: '1:83064937407:ios:d074797eeaa8c8eaa49f0a',
    messagingSenderId: '83064937407',
    projectId: 'myauthentication-534e5',
    storageBucket: 'myauthentication-534e5.appspot.com',
    iosClientId: '83064937407-p14mrgjpuppat9euqcft5aekpaana3e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileNumberAuth',
  );
}
